boards:
  - board_name: main_board
    board_type: nucleo_h753zi
  - board_name: driving_board
    board_type: nucleo_h753zi
testing_options:
  platform: native
  framework: ""
  lib_extra_dirs:
    - ${extra.common_lib_dirs}
  build_src_filter:
    - -<src/>
    - +<lib/common/*>
    - -<lib/common/*/*>
    - +<lib/common/*/native/*>
platformio_options:
  custom_platformio_settings:
    default_envs: driving_board
    src_dir: .
    lib_dir: lib
  custom_extras_settings:
    common_lib_deps:
      - Nanopb
    common_build_flags:
      - -mthumb
      - -mfpu=fpv4-sp-d16
      - -mfloat-abi=softfp
      - -Wl,-u,_printf_float
      - -D CONFIG_LOG_LEVEL=LOG_INFO
    common_lib_dirs:
      - lib/common
  custom_per_env_settings:
    lib_extra_dirs:
      - ${extra.common_lib_dirs}
    build_src_filter:
      - +<src/${this.__env__}/**/*.c>
      - -<lib/common>
      - +<lib/common/*/${this.__env__}/**/*.c>
    custom_nanopb_protos:
      - +<proto/${this.__env__}.proto>
    lib_deps:
      - ${extra.common_lib_deps}
      - lib/${this.__env__}/firmware
  custom_env_settings:
    platform: ststm32
    framework: stm32cube
    custom_nanopb_options: --error-on-unmatched
    test_build_src: true
