[platformio]
default_envs = arm_board
src_dir = .
lib_dir = lib


[extra]
common_lib_deps = Nanopb

[env]
platform = ststm32
framework = stm32cube
custom_nanopb_options = --error-on-unmatched
test_build_src = True

[env:main_board]
board = nucleo_h753zi
build_src_filter = +<src/${this.__env__}/**/*.c>
    +<components/common/*/${this.__env__}/**/*.c>
    +<components/common/*/*.c>
    +<components/main_board/**>
    -<components/main_board/firmware/Drivers/**>
    +<components/main_board/firmware/Drivers/BSP/**>
custom_nanopb_protos = +<proto/${this.__env__}.proto>
    +<proto/common.proto>
lib_deps = ${extra.common_lib_deps}
test_filter = common/*
build_flags=
	-I components/common/logging/inc
	-I components/common/logging
	-I components/common/pb_message
	-I components/common/networking_constants
	-I components/common/result
	-I components/common/kv_pool
	-I components/main_board
	-I components/main_board/diagnostics
	-I components/main_board/timer
	-I components/main_board/timer/src
	-I components/main_board/timer/inc
	-I components/main_board/networking
	-I components/main_board/networking/src
	-I components/main_board/networking/inc
	-I components/main_board/firmware
	-I components/main_board/firmware/Middlewares
	-I components/main_board/firmware/Middlewares/Third_Party
	-I components/main_board/firmware/Middlewares/Third_Party/FreeRTOS
	-I components/main_board/firmware/Middlewares/Third_Party/FreeRTOS/Source
	-I components/main_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/include
	-I components/main_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable
	-I components/main_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang
	-I components/main_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC
	-I components/main_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
	-I components/main_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
	-I components/main_board/firmware/Core
	-I components/main_board/firmware/Core/Src
	-I components/main_board/firmware/Core/Inc
	-I components/main_board/firmware/Drivers
	-I components/main_board/firmware/Drivers/BSP
	-I components/main_board/firmware/Drivers/BSP/STM32H7xx_Nucleo
	-I components/main_board/firmware/Drivers/BSP/Components
	-I components/main_board/firmware/Drivers/BSP/Components/lan8742
	-I components/main_board/firmware/Drivers/STM32H7xx_HAL_Driver
	-I components/main_board/firmware/Drivers/STM32H7xx_HAL_Driver/Src
	-I components/main_board/firmware/Drivers/STM32H7xx_HAL_Driver/Inc
	-I components/main_board/firmware/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy
	-I components/main_board/firmware/Drivers/CMSIS
	-I components/main_board/firmware/Drivers/CMSIS/Include
	-I components/main_board/firmware/Drivers/CMSIS/Device
	-I components/main_board/firmware/Drivers/CMSIS/Device/ST
	-I components/main_board/firmware/Drivers/CMSIS/Device/ST/STM32H7xx
	-I components/main_board/firmware/Drivers/CMSIS/Device/ST/STM32H7xx/Source
	-I components/main_board/firmware/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates
	-I components/main_board/firmware/Drivers/CMSIS/Device/ST/STM32H7xx/Include
	-I components/main_board/firmware/LWIP
	-I components/main_board/firmware/LWIP/App
	-I components/main_board/firmware/LWIP/Target
	-I components/main_board/ssd1306
	-I components/main_board/ssd1306/src
	-I components/main_board/ssd1306/inc
	-I components/main_board/menu_driver
	-I components/main_board/menu_driver/src
	-I components/main_board/menu_driver/inc
	-mthumb
	-mfpu=fpv4-sp-d16
	-mfloat-abi=softfp
	-Wl,-u,_printf_float
	-D CONFIG_LOG_LEVEL=LOG_INFO
	-DUSE_PWR_LDO_SUPPLY 
	-DUSE_NUCLEO_64 
	-DUSE_HAL_DRIVER 
	-DSTM32H753xx 
	-DSTM32_THREAD_SAFE_STRATEGY=4

[env:arm_board]
board = nucleo_h753zi
board_build.stm32cube.custom_config_header = yes
build_src_filter = +<src/${this.__env__}/**/*.c>
    +<components/common/*/${this.__env__}/**/*.c>
    +<components/${this.__env__}/*>
    -<components/${this.__env__}/firmware/Drivers/*>
    +<components/${this.__env__}/firmware/Drivers/BSP/**>
    -<components/${this.__env__}/*/test/*>
custom_nanopb_protos = +<proto/${this.__env__}.proto>
    +<proto/common.proto>
lib_deps = ${extra.common_lib_deps}
build_flags=
	-I components/arm_board
	-I components/arm_board/networking
	-I components/arm_board/networking/src
	-I components/arm_board/networking/inc
	-I components/arm_board/firmware
	-I components/arm_board/firmware/Middlewares
	-I components/arm_board/firmware/Middlewares/Third_Party
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/system
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/system/OS
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/system/arch
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/apps
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/apps/mqtt
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/compat
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/compat/posix
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/compat/posix/net
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/compat/posix/sys
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/compat/stdc
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/lwip
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/lwip/apps
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/lwip/priv
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/lwip/prot
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/netif
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/include/netif/ppp
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/api
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/netif
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/netif/ppp
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/core
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/core/ipv4
	-I components/arm_board/firmware/Middlewares/Third_Party/LwIP/src/core/ipv6
	-I components/arm_board/firmware/Middlewares/Third_Party/FreeRTOS
	-I components/arm_board/firmware/Middlewares/Third_Party/FreeRTOS/Source
	-I components/arm_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/include
	-I components/arm_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable
	-I components/arm_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang
	-I components/arm_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC
	-I components/arm_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
	-I components/arm_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
	-I components/arm_board/firmware/Core
	-I components/arm_board/firmware/Core/Src
	-I components/arm_board/firmware/Core/Inc
	-I components/arm_board/firmware/LWIP
	-I components/arm_board/firmware/LWIP/App
	-I components/arm_board/firmware/LWIP/Target
	-I components/arm_board/firmware_definitions
	-I components/arm_board/firmware/Drivers/BSP
	-I components/arm_board/firmware/Drivers/BSP/STM32H7xx_Nucleo
	-I components/arm_board/firmware/Drivers/BSP/Components
	-I components/arm_board/firmware/Drivers/BSP/Components/lan8742
	-I components/common/logging
	-I components/common/pb_message
	-I components/common/networking_constants
	-I components/common/result
	-I components/common/kv_pool
	-I components/common/logging/inc
	-I components/common/logging/arm_board
	-mthumb
	-mfpu=fpv4-sp-d16
	-mfloat-abi=softfp
	-Wl,-u,_printf_float
	-D CONFIG_LOG_LEVEL=LOG_INFO
	-DUSE_PWR_LDO_SUPPLY 
	-DUSE_NUCLEO_64 
	-DUSE_HAL_DRIVER 
	-DSTM32H753xx

[env:sensor_board]
board = nucleo_h753zi
lib_deps = ${extra.common_lib_deps}
test_filter = sensor_board/*
build_src_filter = +<src/${this.__env__}/**/*.c>
    +<components/common/*/${this.__env__}/**/*.c>
    +<components/common/*.c>
    +<components/sensor_board/**>
    -<components/sensor_board/firmware/Drivers/**>
    +<components/sensor_board/firmware/Drivers/BSP/**>
custom_nanopb_protos = +<proto/${this.__env__}.proto>
    +<proto/common.proto>
build_flags = 
	-I components/common/logging/inc
	-I components/common/logging
	-I components/common/pb_message
	-I components/common/networking_constants
	-I components/common/result
	-I components/common/kv_pool
	-I components/sensor_board
	-I components/sensor_board/imu
	-I components/sensor_board/firmware
	-I components/sensor_board/firmware/Middlewares
	-I components/sensor_board/firmware/Middlewares/Third_Party
	-I components/sensor_board/firmware/Middlewares/Third_Party/FreeRTOS
	-I components/sensor_board/firmware/Middlewares/Third_Party/FreeRTOS/Source
	-I components/sensor_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/include
	-I components/sensor_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable
	-I components/sensor_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang
	-I components/sensor_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC
	-I components/sensor_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
	-I components/sensor_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
	-I components/sensor_board/firmware/Core
	-I components/sensor_board/firmware/Core/Src
	-I components/sensor_board/firmware/Core/Inc
	-I components/sensor_board/ph
	-I components/sensor_board/gps
	-I components/sensor_board/sensor_basics
	-I components/sensor_board/firmware/Drivers/BSP
	-I components/sensor_board/firmware/Drivers/BSP/STM32H7xx_Nucleo
	-mthumb
	-mfpu=fpv4-sp-d16
	-mfloat-abi=softfp
	-Wl,-u,_printf_float
	-D CONFIG_LOG_LEVEL=LOG_INFO
	-DUNITY_INCLUDE_DOUBLE
	-lm
	-DUSE_PWR_LDO_SUPPLY 
	-DUSE_NUCLEO_64 
	-DUSE_HAL_DRIVER 
	-DSTM32H753xx 
	-DSTM32_THREAD_SAFE_STRATEGY=4



[env:driving_board]
board = nucleo_h753zi
build_src_filter = +<src/${this.__env__}/**/*.c>
    +<components/common/*/${this.__env__}/**/*.c>
    +<components/common/*.c>
    +<components/driving_board/**>
    -<components/driving_board/firmware/Drivers/**>
    +<components/driving_board/firmware/Drivers/BSP/**>
custom_nanopb_protos = +<proto/${this.__env__}.proto>
    +<proto/common.proto>
test_filter = driving_board/*
lib_deps = ${extra.common_lib_deps}
build_flags=
	-I components/common/logging/inc
	-I components/common/logging
	-I components/common/pb_message
	-I components/common/networking_constants
	-I components/common/result
	-I components/common/kv_pool
	-I components/driving_board
	-I components/driving_board/motor
	-I components/driving_board/calculator
	-I components/driving_board/firmware
	-I components/driving_board/firmware/Middlewares
	-I components/driving_board/firmware/Middlewares/Third_Party
	-I components/driving_board/firmware/Middlewares/Third_Party/FreeRTOS
	-I components/driving_board/firmware/Middlewares/Third_Party/FreeRTOS/Source
	-I components/driving_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/include
	-I components/driving_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable
	-I components/driving_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang
	-I components/driving_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC
	-I components/driving_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
	-I components/driving_board/firmware/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
	-I components/driving_board/firmware/Core
	-I components/driving_board/firmware/Core/Src
	-I components/driving_board/firmware/Core/Inc
	-I components/driving_board/simulink
	-I components/driving_board/parser
	-I components/driving_board/firmware/Drivers/BSP
	-I components/driving_board/firmware/Drivers/BSP/STM32H7xx_Nucleo
	-mthumb
	-mfpu=fpv4-sp-d16
	-mfloat-abi=softfp
	-Wl,-u,_printf_float
	-D CONFIG_LOG_LEVEL=LOG_INFO
	-DUSE_PWR_LDO_SUPPLY 
	-DUSE_NUCLEO_64 
	-DUSE_HAL_DRIVER 
	-DSTM32H753xx 
	-DSTM32_THREAD_SAFE_STRATEGY=4
