; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = embed_board
src_dir = .


[env:embed_board]
board=nucleo_h753zi
platform=ststm32
framework=stm32cube
build_src_filter=
  +<drivers/**>
  -<drivers/driving_board/firmware/Drivers/**>
  +<drivers/driving_board/firmware/Drivers/BSP/**>
  +<src/**>

build_flags=
	-I drivers/driving_board
	-I drivers/driving_board/calculator
	-I drivers/driving_board/firmware
	-I drivers/driving_board/firmware/Middlewares
	-I drivers/driving_board/firmware/Core
	-I drivers/driving_board/firmware/Core/Src
	-I drivers/driving_board/firmware/Core/Inc
	-I drivers/driving_board/firmware/Drivers/BSP
	-I drivers/driving_board/firmware/Drivers/BSP/STM32H7xx_Nucleo
	-I drivers/common/logging/inc
	-I drivers/common/logging/driving_board
	-mthumb
	-mfpu=fpv4-sp-d16
	-mfloat-abi=softfp
	-Wl,-u,_printf_float
	-D CONFIG_LOG_LEVEL=LOG_INFO


[env:test_embed_board]
board=nucleo_h753zi
platform=ststm32
framework=stm32cube
monitor_speed = 115200
debug_tool = stlink
build_type = debug

build_src_filter=
  +<drivers/**>
  -<drivers/driving_board/firmware/Drivers/**>
  +<drivers/driving_board/firmware/Drivers/BSP/**>
  
test_filter=driving_board/**
debug_test = driving_board/test_calculator
test_build_src = true
build_flags=
	-I drivers/driving_board
	-I drivers/driving_board/calculator
	-I drivers/driving_board/firmware
	-I drivers/driving_board/firmware/Core
	-I drivers/driving_board/firmware/Core/Src
	-I drivers/driving_board/firmware/Core/Inc
	-I drivers/driving_board/firmware/Drivers/BSP
	-I drivers/driving_board/firmware/Drivers/BSP/STM32H7xx_Nucleo
	-I drivers/common/logging/inc
	-I drivers/common/logging/driving_board
	-mthumb
	-mfpu=fpv4-sp-d16
	-mfloat-abi=softfp
	-Wl,-u,_printf_float
	-D CONFIG_LOG_LEVEL=LOG_INFO



