[platformio]
default_envs = container_board
src_dir = .
lib_dir = lib


[extra]
common_lib_deps = Nanopb
common_build_flags = -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -Wl,-u,_printf_float
    -D CONFIG_LOG_LEVEL=LOG_INFO


[env]
platform = ststm32
framework = stm32cube
custom_nanopb_options = --error-on-unmatched
test_build_src = True

[env:container_board]
board = nucleo_h753zi
build_src_filter = +<src/${this.__env__}/**/*.c>
    -<components/common>
    +<components/common/*/${this.__env__}/**/*.c>
    +<components/container_board/**>
    -<components/container_board/firmware/Drivers/**>
    +<components/container_board/firmware/Drivers/BSP/**>
custom_nanopb_protos = +<proto/${this.__env__}.proto>
    +<proto/common.proto>
lib_deps = ${extra.common_lib_deps}
build_flags=
    -I components/container_board
    -I components/container_board\lock
    -I components/container_board\scale
    -I components/common/logging/inc
    -I components/common/logging/container_board
    -I components/common/networking_constants
    -I components/common/pb_message
    -I components/common/result
    -I components/container_board/lock
    -I components/container_board/scale
    -I components/container_board/firmware
	  -I components/container_board/firmware/Core
	  -I components/container_board/firmware/Core/Src
	  -I components/container_board/firmware/Core/Inc
	  -I components/container_board/firmware/Drivers/BSP
	  -I components/container_board/firmware/Drivers/BSP/STM32H7xx_Nucleo
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -Wl,-u,_printf_float
    -D CONFIG_LOG_LEVEL=LOG_INFO
