#ifndef MENU_DRIVER_CONF_H
#define MENU_DRIVER_CONF_H

#define MENU_DRIVER_BACKGROUND_COLOR 0x0000 // Black
#define MENU_DRIVER_FOREGROUND_COLOR 0xFFFF // White

#define MENU_SIDEBAR_WIDTH 38

#define MAX_LIST_ENTRIES 10
#define MAX_LIST_TITLE_LEN 24
#define MAX_PAGE_NAME_LEN 20

#define MENU_OVERVIEW_MAX_ENTRIES 10
#define MENU_OVERVIEW_MAX_ENTRY_TITLE_LEN 12
#endif // !MENU_DRIVER_CONF_H
