#ifndef NETWORKING_CONSTANTS_H
#define NETWORKING_CONSTANTS_H

#include "../networking/stm/ethernet_udp.h"

// BOARD IDS

#define DEBUGGING_BOARD_ID 0x01
#define WIRELESS_BOARD_ID 0x02
#define SENSOR_BOARD_ID 0x03
#define PROCESSING_BOARD_ID 0x04
#define DRIVING_BOARD_ID 0x05
#define ROBOTIC_ARM_ID 0x06
#define SURFACE_SAMPLE_CONTAINER_ID 0x07

// PACKET IDS

// ETHERNET CONFIGURATION
#define ETHERNET_RQ_LENGTH 80
#define ETHERNET_RQ_ITEM_SIZE sizeof(receive_frame_t)
#define ETHERNET_RQ_PRIORITY_BUFFERS 2

#define ETHERNET_SQ_LENGTH 80
#define ETHERNET_SQ_ITEM_SIZE sizeof(udp_send_frame_t)
#define ETHERNET_SQ_PRIORITY_BUFFERS 2
#define MAX_ETH_PAYLOAD_SIZE 80
#endif // !NETWORKING_CONSTANTS_H
