#ifndef NETWORKING_CONSTANTS_H
#define NETWORKING_CONSTANTS_H

// BOARD IDS

#define DEBUGGING_BOARD_ID 0x01
#define WIRELESS_BOARD_ID 0x02
#define SENSOR_BOARD_ID 0x03
#define PROCESSING_BOARD_ID 0x04
#define DRIVING_BOARD_ID 0x05
#define ROBOTIC_ARM_ID 0x06
#define SURFACE_SAMPLE_CONTAINER_ID 0x07

// PACKET IDS

// EHTERNET CONFIGURATION
#define ETHERNET_RQ_LENGTH 80
#define ETHERNET_RQ_ITEM_SIZE sizeof(uint64_t)
#define ETHERNET_RQ_PRIORITY_BUFFERS 2
#endif // !NETWORKING_CONSTANTS_H
