
#define CUBEMARS_AK_FRAME_HEADER 0x02u
#define CUBEMARS_AK_FRAME_TAIL 0x03u

#define CUBEMARS_AK_CAN_FEEDBACK_DLC FDCAN_DLC_BYTES_8
#define CUBEMARS_AK_CAN_SERVO_FEEDBACK_ID 0x29u

// Flag indexes for requesting data
#define CUBEMARS_AK_PARAM_MOS_TEMPERATURE_BIT 0u
#define CUBEMARS_AK_PARAM_MOTOR_TEMPERATURE_BIT 1u
#define CUBEMARS_AK_PARAM_OUTPUT_CURRENT_BIT 2u
#define CUBEMARS_AK_PARAM_INPUT_CURRENT_BIT 3u
#define CUBEMARS_AK_PARAM_ID_CURRENT_BIT 4u
#define CUBEMARS_AK_PARAM_IQ_CURRENT_BIT 5u
#define CUBEMARS_AK_PARAM_DUTY_CYCLE_BIT 6u
#define CUBEMARS_AK_PARAM_MOTOR_SPEED_BIT 7u
#define CUBEMARS_AK_PARAM_INPUT_VOLTAGE_BIT 8u

#define CUBEMARS_AK_PARAM_RESERVED_9_BIT 9u
#define CUBEMARS_AK_PARAM_RESERVED_10_BIT 10u
#define CUBEMARS_AK_PARAM_RESERVED_11_BIT 11u
#define CUBEMARS_AK_PARAM_RESERVED_12_BIT 12u
#define CUBEMARS_AK_PARAM_RESERVED_13_BIT 13u
#define CUBEMARS_AK_PARAM_RESERVED_14_BIT 14u

#define CUBEMARS_AK_PARAM_STATUS_CODE_BIT 15u
#define CUBEMARS_AK_PARAM_MOTOR_POSITION_BIT 16u
#define CUBEMARS_AK_PARAM_MOTOR_ID_BIT 17u

#define CUBEMARS_AK_PARAM_RESERVED_18_BIT 18u
#define CUBEMARS_AK_PARAM_RESERVED_19_BIT 19u
#define CUBEMARS_AK_PARAM_RESERVED_20_BIT 20u
#define CUBEMARS_AK_PARAM_RESERVED_21_BIT 21u
#define CUBEMARS_AK_PARAM_RESERVED_22_BIT 22u
#define CUBEMARS_AK_PARAM_RESERVED_23_BIT 23u
#define CUBEMARS_AK_PARAM_RESERVED_24_BIT 24u
#define CUBEMARS_AK_PARAM_RESERVED_25_BIT 25u
#define CUBEMARS_AK_PARAM_RESERVED_26_BIT 26u
#define CUBEMARS_AK_PARAM_RESERVED_27_BIT 27u
#define CUBEMARS_AK_PARAM_RESERVED_28_BIT 28u
#define CUBEMARS_AK_PARAM_RESERVED_29_BIT 29u
#define CUBEMARS_AK_PARAM_RESERVED_30_BIT 30u
#define CUBEMARS_AK_PARAM_RESERVED_31_BIT 31u

#define CUBEMARS_AK_CAN_POSITION_SCALE 10
#define CUBEMARS_AK_CAN_SPEED_SCALE 10
#define CUBEMARS_AK_CAN_CURRENT_SCALE 100
#define CUBEMARS_AK_CAN_TEMPERATURE_SCALE 1
#define CUBEMARS_AK_CAN_STATUS_SCALE 1

// Flag insertion macros

#define CUBEMARS_AK_PARAM_MOS_TEMPERATURE_MASK \
    (1u << CUBEMARS_AK_PARAM_MOS_TEMPERATURE_BIT)

#define CUBEMARS_AK_PARAM_MOTOR_TEMPERATURE_MASK \
    (1u << CUBEMARS_AK_PARAM_MOTOR_TEMPERATURE_BIT)

#define CUBEMARS_AK_PARAM_OUTPUT_CURRENT_MASK \
    (1u << CUBEMARS_AK_PARAM_OUTPUT_CURRENT_BIT)

#define CUBEMARS_AK_PARAM_INPUT_CURRENT_MASK \
    (1u << CUBEMARS_AK_PARAM_INPUT_CURRENT_BIT)

#define CUBEMARS_AK_PARAM_ID_CURRENT_MASK \
    (1u << CUBEMARS_AK_PARAM_ID_CURRENT_BIT)

#define CUBEMARS_AK_PARAM_IQ_CURRENT_MASK \
    (1u << CUBEMARS_AK_PARAM_IQ_CURRENT_BIT)

#define CUBEMARS_AK_PARAM_DUTY_CYCLE_MASK \
    (1u << CUBEMARS_AK_PARAM_DUTY_CYCLE_BIT)

#define CUBEMARS_AK_PARAM_MOTOR_SPEED_MASK \
    (1u << CUBEMARS_AK_PARAM_MOTOR_SPEED_BIT)

#define CUBEMARS_AK_PARAM_INPUT_VOLTAGE_MASK \
    (1u << CUBEMARS_AK_PARAM_INPUT_VOLTAGE_BIT)

#define CUBEMARS_AK_PARAM_STATUS_CODE_MASK \
    (1u << CUBEMARS_AK_PARAM_STATUS_CODE_BIT)

#define CUBEMARS_AK_PARAM_MOTOR_POSITION_MASK \
    (1u << CUBEMARS_AK_PARAM_MOTOR_POSITION_BIT)

#define CUBEMARS_AK_PARAM_MOTOR_ID_MASK (1u << CUBEMARS_AK_PARAM_MOTOR_ID_BIT)

// Scaling factors of data

#define CUBEMARS_AK_MOS_TEMPERATURE_SCALE 10
#define CUBEMARS_AK_MOTOR_TEMPERATURE_SCALE 10

#define CUBEMARS_AK_OUTPUT_CURRENT_SCALE 100
#define CUBEMARS_AK_INPUT_CURRENT_SCALE 100
#define CUBEMARS_AK_ID_CURRENT_SCALE 100
#define CUBEMARS_AK_IQ_CURRENT_SCALE 100

#define CUBEMARS_AK_DUTY_CYCLE_SCALE 1000
#define CUBEMARS_AK_MOTOR_SPEED_SCALE 1
#define CUBEMARS_AK_INPUT_VOLTAGE_SCALE 10

#define CUBEMARS_AK_STATUS_CODE_SCALE 1
#define CUBEMARS_AK_MOTOR_POSITION_SCALE 1000000
#define CUBEMARS_AK_MOTOR_ID_SCALE 1
